config/routes.rb
SurveyForm::Engine.routes.draw do
  root 'forms#index'

  resources :forms
end

app/models/survey_form/application_record.rb
module SurveyForm
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/survey_form/field.rb
module SurveyForm
  class Field < ApplicationRecord
    attr_accessor :skip_validation

    TYPES = %w[SurveyForm::Fields::TextField SurveyForm::Fields::NoteField SurveyForm::Fields::IntegerField SurveyForm::Fields::DateField SurveyForm::Fields::DateTimeField SurveyForm::Fields::SelectOneField SurveyForm::Fields::SelectMultipleField SurveyForm::Fields::ImageField SurveyForm::Fields::FileField SurveyForm::Fields::LocationField SurveyForm::Fields::MappingField].freeze

    # Association
    belongs_to :section, class_name: 'SurveyForm::Section'
    belongs_to :parent, foreign_key: :mapping_field_id, class_name: 'SurveyForm::Field', optional: true
    has_many   :field_options, class_name: 'SurveyForm::FieldOption', dependent: :destroy
    # has_many   :field_values

    # Validation
    validates :code, presence: true, uniqueness: { scope: :section_id, message: 'already exist' }
    validates :name, presence: true, uniqueness: { scope: :section_id, message: 'already exist' }
    validates :type, presence: true, inclusion: { in: TYPES }
    validates :mapping_field_id, presence: true, if: -> { type == 'SurveyForm::Fields::MappingField' && !skip_validation }

    before_validation :set_field_code, if: -> { name.present? }
    # before_validation :set_mapping_field_type
    before_validation :set_form
    before_create :set_display_order

    # Nested attributes
    accepts_nested_attributes_for :field_options, allow_destroy: true, reject_if: ->(attributes) { attributes['name'].blank? }

    serialize :validations, Hash

    def kind
      raise 'you have to implement in subclass'
    end

    def self.es_datatype
      raise 'you have to implement in subclass'
    end

    def format_name
      name.downcase.split(' ').join('_')
    end

    private
      def set_field_code
        self.code ||= format_name
      end

      def set_display_order
        self.display_order ||= section.present? && section.fields.maximum(:display_order).to_i + 1
      end

      def set_form
        self.form_id = section.form_id if section
      end

      def set_mapping_field_type
        # return unless field_type == 'mapping_field'

        # event_mapping_field = self.class.roots.find { |obj| obj[:code] == mapping_field }
        # self.mapping_field_type = event_mapping_field.present? && event_mapping_field[:field_type]
        # self.color_required = event_mapping_field.present? && event_mapping_field[:color_required]
      end
  end
end

app/models/survey_form/field_option.rb
module SurveyForm
  class FieldOption < ApplicationRecord
    belongs_to :field, class_name: 'SurveyForm::Field', foreign_key: :field_id

    # Validation
    validates :value, :name, presence: true, uniqueness: { scope: [:field_id] }
    before_validation :set_option_value, if: -> { name.present? }

    private
      def set_option_value
        self.value = (value.presence || name).downcase.split(' ').join('_')
      end
  end
end

app/models/survey_form/fields/date_field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id                 :bigint           not null, primary key
#  code               :string
#  color_required     :boolean          default(FALSE)
#  description        :text
#  display_order      :integer
#  entry_able         :boolean          default(TRUE)
#  field_type         :string
#  is_default         :boolean          default(FALSE)
#  mapping_field      :string
#  mapping_field_type :string
#  name               :string
#  relevant           :string
#  required           :boolean
#  tracking           :boolean          default(FALSE)
#  validations        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  mapping_field_id   :integer
#  milestone_id       :integer
#  section_id         :integer
#
module SurveyForm
  module Fields
    class DateField < ::SurveyForm::Field
      def kind
        :date
      end

      def self.es_datatype
        :date
      end
    end
  end
end

app/models/survey_form/fields/date_time_field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id                 :bigint           not null, primary key
#  code               :string
#  color_required     :boolean          default(FALSE)
#  description        :text
#  display_order      :integer
#  entry_able         :boolean          default(TRUE)
#  field_type         :string
#  is_default         :boolean          default(FALSE)
#  mapping_field      :string
#  mapping_field_type :string
#  name               :string
#  relevant           :string
#  required           :boolean
#  tracking           :boolean          default(FALSE)
#  validations        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  mapping_field_id   :integer
#  milestone_id       :integer
#  section_id         :integer
#
module SurveyForm
  module Fields
    class DateTimeField < ::SurveyForm::Field
      def kind
        :date_time
      end

      def self.es_datatype
        :date
      end
    end
  end
end

app/models/survey_form/fields/file_field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id                 :bigint           not null, primary key
#  code               :string
#  color_required     :boolean          default(FALSE)
#  description        :text
#  display_order      :integer
#  entry_able         :boolean          default(TRUE)
#  field_type         :string
#  is_default         :boolean          default(FALSE)
#  mapping_field      :string
#  mapping_field_type :string
#  name               :string
#  relevant           :string
#  required           :boolean
#  tracking           :boolean          default(FALSE)
#  validations        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  mapping_field_id   :integer
#  milestone_id       :integer
#  section_id         :integer
#
module SurveyForm
  module Fields
    class FileField < ::SurveyForm::Field
      def kind
        :file
      end

      def self.es_datatype
        :text
      end
    end
  end
end

app/models/survey_form/fields/image_field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id                 :bigint           not null, primary key
#  code               :string
#  color_required     :boolean          default(FALSE)
#  description        :text
#  display_order      :integer
#  entry_able         :boolean          default(TRUE)
#  field_type         :string
#  is_default         :boolean          default(FALSE)
#  mapping_field      :string
#  mapping_field_type :string
#  name               :string
#  relevant           :string
#  required           :boolean
#  tracking           :boolean          default(FALSE)
#  validations        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  mapping_field_id   :integer
#  milestone_id       :integer
#  section_id         :integer
#

module SurveyForm
  module Fields
    class ImageField < ::SurveyForm::Field
      def kind
        :image
      end

      def self.es_datatype
        :text
      end
    end
  end
end

app/models/survey_form/fields/integer_field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id                 :bigint           not null, primary key
#  code               :string
#  color_required     :boolean          default(FALSE)
#  description        :text
#  display_order      :integer
#  entry_able         :boolean          default(TRUE)
#  field_type         :string
#  is_default         :boolean          default(FALSE)
#  mapping_field      :string
#  mapping_field_type :string
#  name               :string
#  relevant           :string
#  required           :boolean
#  tracking           :boolean          default(FALSE)
#  validations        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  mapping_field_id   :integer
#  milestone_id       :integer
#  section_id         :integer
#

module SurveyForm
  module Fields
    class IntegerField < ::SurveyForm::Field
      def kind
        :integer
      end

      def self.es_datatype
        :integer
      end
    end
  end
end

app/models/survey_form/fields/location_field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id                 :bigint           not null, primary key
#  code               :string
#  color_required     :boolean          default(FALSE)
#  description        :text
#  display_order      :integer
#  entry_able         :boolean          default(TRUE)
#  field_type         :string
#  is_default         :boolean          default(FALSE)
#  mapping_field      :string
#  mapping_field_type :string
#  name               :string
#  relevant           :string
#  required           :boolean
#  tracking           :boolean          default(FALSE)
#  validations        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  mapping_field_id   :integer
#  milestone_id       :integer
#  section_id         :integer
#

module SurveyForm
  module Fields
    class LocationField < ::SurveyForm::Field
      def kind
        :location
      end

      def self.es_datatype
        :keyword
      end
    end
  end
end

app/models/survey_form/fields/mapping_field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id                 :bigint           not null, primary key
#  code               :string
#  color_required     :boolean          default(FALSE)
#  description        :text
#  display_order      :integer
#  entry_able         :boolean          default(TRUE)
#  field_type         :string
#  is_default         :boolean          default(FALSE)
#  mapping_field      :string
#  mapping_field_type :string
#  name               :string
#  relevant           :string
#  required           :boolean
#  tracking           :boolean          default(FALSE)
#  validations        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  mapping_field_id   :integer
#  milestone_id       :integer
#  section_id         :integer
#

module SurveyForm
  module Fields
    class MappingField < ::SurveyForm::Field
      def kind
        :mapping
      end

      def self.es_datatype
        :text
      end
    end
  end
end

app/models/survey_form/fields/note_field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id                 :bigint           not null, primary key
#  code               :string
#  color_required     :boolean          default(FALSE)
#  description        :text
#  display_order      :integer
#  entry_able         :boolean          default(TRUE)
#  field_type         :string
#  is_default         :boolean          default(FALSE)
#  mapping_field      :string
#  mapping_field_type :string
#  name               :string
#  relevant           :string
#  required           :boolean
#  tracking           :boolean          default(FALSE)
#  validations        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  mapping_field_id   :integer
#  milestone_id       :integer
#  section_id         :integer
#

module SurveyForm
  module Fields
    class NoteField < ::SurveyForm::Field
      def kind
        :note
      end

      def self.es_datatype
        :text
      end
    end
  end
end

app/models/survey_form/fields/select_multiple_field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id                 :bigint           not null, primary key
#  code               :string
#  color_required     :boolean          default(FALSE)
#  description        :text
#  display_order      :integer
#  entry_able         :boolean          default(TRUE)
#  field_type         :string
#  is_default         :boolean          default(FALSE)
#  mapping_field      :string
#  mapping_field_type :string
#  name               :string
#  relevant           :string
#  required           :boolean
#  tracking           :boolean          default(FALSE)
#  validations        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  mapping_field_id   :integer
#  milestone_id       :integer
#  section_id         :integer
#

module SurveyForm
  module Fields
    class SelectMultipleField < ::SurveyForm::Field
      def kind
        :select_multiple
      end

      def self.es_datatype
        :text
      end
    end
  end
end

app/models/survey_form/fields/select_one_field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id                 :bigint           not null, primary key
#  code               :string
#  color_required     :boolean          default(FALSE)
#  description        :text
#  display_order      :integer
#  entry_able         :boolean          default(TRUE)
#  field_type         :string
#  is_default         :boolean          default(FALSE)
#  mapping_field      :string
#  mapping_field_type :string
#  name               :string
#  relevant           :string
#  required           :boolean
#  tracking           :boolean          default(FALSE)
#  validations        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  mapping_field_id   :integer
#  milestone_id       :integer
#  section_id         :integer
#

module SurveyForm
  module Fields
    class SelectOneField < ::SurveyForm::Field
      def kind
        :select_one
      end

      def self.es_datatype
        :text
      end
    end
  end
end

app/models/survey_form/fields/text_field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: fields
#
#  id                 :bigint           not null, primary key
#  code               :string
#  color_required     :boolean          default(FALSE)
#  description        :text
#  display_order      :integer
#  entry_able         :boolean          default(TRUE)
#  field_type         :string
#  is_default         :boolean          default(FALSE)
#  mapping_field      :string
#  mapping_field_type :string
#  name               :string
#  relevant           :string
#  required           :boolean
#  tracking           :boolean          default(FALSE)
#  validations        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  mapping_field_id   :integer
#  milestone_id       :integer
#  section_id         :integer
#

module SurveyForm
  module Fields
    class TextField < ::SurveyForm::Field
      def kind
        :text
      end

      def self.es_datatype
        :text
      end
    end
  end
end

app/models/survey_form/form.rb
module SurveyForm
  class Form < ApplicationRecord
    has_many :sections, class_name: 'SurveyForm::Section'
    has_many :fields, through: :sections

    accepts_nested_attributes_for :sections, allow_destroy: true, reject_if: ->(attributes) { attributes['name'].blank? }
  end
end

app/controllers/survey_form/application_controller.rb
module SurveyForm
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

app/controllers/survey_form/forms_controller.rb
require_dependency "survey_form/application_controller"

module SurveyForm
  class FormsController < ApplicationController
    def index
      @forms = SurveyForm::Form.all
    end

    def show
      @form = SurveyForm::Form.find(params[:id])
    end

    def new
      @form = SurveyForm::Form.new
    end

    def create
      @form = SurveyForm::Form.new(form_params)

      if @form.save
        redirect_to forms_url
      else
        flash.now[:alert] = @form.errors.full_messages
        render :new
      end
    end

    def edit
      @form = SurveyForm::Form.find(params[:id])
      @form.fields.new
    end

    def update
      @form = SurveyForm::Form.find(params[:id])

      if @form.update(form_params)
        redirect_to survey_form.forms_url
      else
        flash.now[:alert] = @form.errors.full_messages
        render :edit
      end
    end

    def destroy
      @form = SurveyForm::Form.find(params[:id])
      @form.destroy

      redirect_to survey_form.forms_url
    end

    private
      def form_params
        params.require(:form).permit(
          :name, :display_order,
          sections_attributes: [
            :id, :name, :default, :_destroy, :display,
            fields_attributes: [
              :id, :name, :type, :required, :display_order, :code, :entry_able,
              :mapping_field_id, :_destroy, :tracking, :description, :relevant,
              validations: {},
              field_options_attributes: %i[id name value color _destroy]
            ]
          ]
        )
      end
  end
end

app/helpers/survey_form/application_helper.rb
module SurveyForm
  module ApplicationHelper
    def link_to_add_fields(name, f, association, option = {})
      new_object = f.object.send(association).klass.new
      id = new_object.object_id

      fields = f.fields_for(association, new_object, child_index: id) do |builder|
        render(association.to_s.singularize + '_fields', f: builder, option: option)
      end

      link_to(name, '#', class: "add_#{association} btn", data: { id: id, fields: fields.gsub("\n", '') })
    end
  end
end

app/helpers/survey_form/forms_helper.rb
module SurveyForm
  module FormsHelper
  end
end

app/views/survey_form/forms/_field_fields.html.haml
%li
  %fieldset.fieldset
    .field-wrapper
      %button.btn.move{type: :button}
        %i.fa.fa-arrows-alt

      .d-flex.flex-grow-1
        .wrapper.d-flex.align-items-center.flex-grow-1
          %button.btn.collapse-trigger{type: :button}
            %i.fas.fa-caret-right

          %abbr.abbr-required{:title => "required", class: ('d-none' if !f.object.required?)} *

          .flex-grow-1
            = f.hidden_field :type, class: 'field-type', 'data-field' => f.object.to_json
            = f.hidden_field :display_order, class: 'display-order'
            = f.text_field :name, placeholder: t('form.field_name'), class: 'form-control field-name'

            - if error_msg = f.object.errors[:name].presence
              .error-message.text-danger.small= error_msg.join('; ')

            = f.text_field :description, placeholder: t('form.field_hint'), class: "form-control field-definition no-style as-hint"

          %button.btn.btn-outline-primary.btn-add-field{type: 'button'}= t('form.add_field')

        .action.d-flex.flex-column
          = f.hidden_field :_destroy

          .btn-setting.pointer.flex-grow-1.d-flex.align-items-center.justify-content-center
            %i.fas.fa-cog.icon-gray

          .remove_fields.pointer.flex-grow-1.d-flex.align-items-center.justify-content-center
            %i.fas.fa-trash-alt.icon-delete

    = render 'kinds'

    .collapse-content
      / = render 'mapping_field_content', f: f

      .options-wrapper
        = f.fields_for :field_options do |builder|
          = render 'field_option_fields', f: builder

        = link_to_add_fields t('form.add_option'), f, :field_options

    .setting-wrapper
      = render 'setting', f: f

app/views/survey_form/forms/_field_option_fields.haml
%fieldset
  .field-wrapper{style: 'margin-top: 10px'}
    = f.hidden_field :_destroy
    = link_to '#', class: "remove_fields btn btn-link" do
      %i.fa.fa-trash-alt.icon-delete
    .d-flex.flex-grow-1
      .flex-grow-1
        = f.text_field :name, placeholder: "option", class: 'form-control'

      .flex-grow-1.d-flex.align-items-center
        %label{style: 'margin: 0 10px 0 20px'}= t('milestone.value')
        = f.text_field :value, placeholder: "option", class: 'form-control'

      .flex-grow-1.field-option-color-wrapper
        .flex-row-vertical-center{style: 'height: 100%'}
          %label= t('milestone.color')
          = f.text_field :color, class: 'field-option-color form-control'

app/views/survey_form/forms/_field_validation_content.haml
.field-validation-wrapper
  .flex-column
    %label.label-header= t('milestone.set_validation')

    = f.fields_for :validations, OpenStruct.new(f.object.validations) do |ff|
      .type-validation.flex-row{'data-validation_type' => 'Survey::Fields::IntegerField'}
        .flex-row-vertical-center.flex1.add-margin
          %label.add-margin= t('milestone.from')
          = ff.number_field :from, placeholder: 'number', class: 'form-control flex1 '

        .flex-row-vertical-center.flex1
          %label.add-margin= t('milestone.to')
          = ff.number_field :to, placeholder: 'number', class: 'form-control flex1'

      .type-validation.flex-row{'data-validation_type' => 'Survey::Fields::DateField'}
        .flex-row-vertical-center.flex1.add-margin
          %label.add-margin= t('milestone.from')
          .input-group.date{'data-provide' => 'datepicker'}
            = ff.text_field :from, placeholder: "yyyy-mm-dd", class: 'form-control'
            .input-group-append
              .input-group-text
                %i.fas.fa-calendar-alt

        .flex-row-vertical-center.flex1
          %label.add-margin= t('milestone.to')
          .input-group.date{'data-provide' => 'datepicker'}
            = ff.text_field :to, placeholder: "yyyy-mm-dd", class: 'form-control'
            .input-group-append
              .input-group-text
                %i.fas.fa-calendar-alt

      .type-validation.flex-row{'data-validation_type' => 'Survey::Fields::DateTimeField'}
        .flex-row-vertical-center.flex1.add-margin
          %label.add-margin= t('milestone.from')
          .input-group{'data-target-input' => 'nearest'}
            - id = "milestone_fields_attributes_#{f.index}1_validations_from"
            = ff.text_field :from, class: 'form-control datetimepicker from', autocomplete: 'off', id: id, data: { target: "##{id}", toggle: 'datetimepicker'}, placeholder: 'yyyy-mm-dd hh:mm'
            .input-group-append{'data-target' => "##{id}", 'data-toggle' => 'datetimepicker'}
              .input-group-text
                %i.far.fa-clock

        .flex-row-vertical-center.flex1
          %label.add-margin= t('milestone.to')
          .input-group{'data-target-input' => 'nearest'}
            - id = "milestone_fields_attributes_#{f.index}2_validations_to"
            = ff.text_field :to, class: 'form-control datetimepicker to', autocomplete: 'off', id: id, data: { target: "##{id}", toggle: 'datetimepicker'}, placeholder: 'yyyy-mm-dd hh:mm'
            .input-group-append{'data-target' => "##{id}", 'data-toggle' => 'datetimepicker'}
              .input-group-text
                %i.far.fa-clock

      - if error_msg = f.object.name.present? && @form.errors[f.object.name.downcase].presence
        .invalid-feedback{style: 'display: block'}= error_msg.join('; ')

app/views/survey_form/forms/_form.html.haml
= simple_form_for @form, class: 'form survey-form' do |f|
  = f.input :name

  - sections = f.object.sections.select{ |section| !section.default }

  = f.fields_for :sections, sections do |sf|
    = render 'section_fields', f: sf

  = link_to_add_fields t('form.add_section'), f, :sections

  .actions
    = f.submit t('shared.save'), class: 'btn btn-primary'
    = link_to t('shared.cancel'), forms_path, class: 'btn btn-secondary'

  :javascript
    locale = {
      please_select: "#{t('form.please_select')}",
      skip_logic_not: "#{t('form.skip_logic_not')}",
      any_of: "#{t('form.any_of')}",
      match_all_of: "#{t('form.match_all_of')}"
    }

app/views/survey_form/forms/_kinds.html.haml
.field-type-wrapper
  .d-flex
    .flex-grow-1
      .field-type-list{'data-field_type' => 'SurveyForm::Fields::SelectOneField'}
        %i.far.fa-dot-circle.icon
        Select one

      .field-type-list{'data-field_type' => 'SurveyForm::Fields::SelectMultipleField'}
        %i.fas.fa-list-ul.icon
        Select Multiple

      .field-type-list{'data-field_type' => 'SurveyForm::Fields::DateField'}
        %i.fas.fa-calendar-alt.icon
        Date

      .field-type-list{'data-field_type' => 'SurveyForm::Fields::DateTimeField'}
        %i.far.fa-clock.icon
        DateTime

      .field-type-list{'data-field_type' => 'SurveyForm::Fields::IntegerField'}
        %strong.icon 123
        Integer

    .flex-grow-1
      .field-type-list{'data-field_type' => 'SurveyForm::Fields::NoteField'}
        %i.fas.fa-bars.icon
        Note
      .field-type-list{'data-field_type' => 'SurveyForm::Fields::TextField'}
        %strong.icon abc
        Text

      .field-type-list{'data-field_type' => 'SurveyForm::Fields::ImageField'}
        %i.fas.fa-image.icon
        Image

      .field-type-list{'data-field_type' => 'SurveyForm::Fields::LocationField'}
        %i.fas.fa-map-marker-alt.icon
        Location

      .field-type-list{'data-field_type' => 'SurveyForm::Fields::FileField'}
        %i.fas.fa-paperclip.icon
        File

    / - if current_program.milestones.first != @milestone
    /   .flex-grow-1
    /     .field-type-list{'data-field_type' => 'SurveyForm::Fields::MappingField'}
    /       %i.fas.fa-exchange-alt.icon
    /       Mapping field

app/views/survey_form/forms/_section_fields.html.haml
%fieldset.section
  %legend.d-inline
    .d-inline-block
      = f.input :name, label: false, placeholder: t('form.section_name')
      = f.hidden_field :default

    .d-inline-block.form-check.form-check-inline
      = f.input :display, label: t('form.display_as_section'), input_html: {class: 'form-check-inline'}

    .d-inline-block.action.remove-section{'data-confirm' => t('form.are_you_sure_to_delete_section')}
      = f.hidden_field :_destroy
      = link_to '#', class: "remove_fields btn btn-link" do
        %i.fa.fa-trash-alt.icon-delete

  %ol.fields.sortable
    = f.fields_for :fields, f.object.fields do |builder|
      = render 'field_fields', f: builder

    = link_to_add_fields t('form.add_field'), f, :fields

app/views/survey_form/forms/_setting.html.haml
.d-flex
  %ul.d-flex.flex-column.items
    %li.item.item-setting{'data-target' => '.setting-content'}= t('form.setting')
    %li.item.validation-trigger{'data-target' => '.validation-criteria-content'}= t('form.validation_criteria')
    %li.item.skip-logic{'data-target' => '.skip-logic-content'}= t('form.skip_logic')

  .contents
    .content.setting-content
      .form-check
        = f.check_box :required, { class: 'form-check-input field-required' }
        = f.label :required, t('form.required'), class: 'form-check-label required-label'

      .form-check
        = f.check_box :tracingable, { class: 'form-check-input' }
        = f.label :tracingable, t('form.tracingable'), class: 'form-check-label'

    .content.validation-criteria-content
      = render 'field_validation_content', f: f

    .content.skip-logic-content
      = f.hidden_field :relevant, class: 'skip-logic-field'
      .form-group.row
        %label.col-3=t('form.question')
        %select#relevant-code.form-control.col-9
      .form-group.row
        %label.col-3=t('form.condition')
        %select#relevant-operator.form-control.col-9
      .form-group.row
        %label.col-3=t('form.value')
        %textarea#relevant-value.form-control.relevant-value.col-9

app/views/survey_form/forms/edit.html.haml
.d-flex.justify-content-center.py-4
  .w-75
    %h1 Edit Form

    = render 'form'

app/views/survey_form/forms/index.html.haml
.d-flex.justify-content-center.py-4
  .w-75
    .d-flex.justify-content-end
      = link_to '+ Add Form', new_form_path, class: 'btn btn-primary mb-4'

    %table.table
      %thead
        %tr
          %th{:scope => "col"} #
          %th{:scope => "col"} Name
          %th{:scope => "col"}
      %tbody
        - @forms.each_with_index do |form, index|
          %tr
            %th{:scope => "row"}= index + 1
            %td= link_to form.name, edit_form_path(form)
            %td
              = link_to edit_form_path(form), class: "btn-circle btn-sm btn-warning text-decoration-none mr-1" do
                %i.fas.fa-edit

              = link_to form_path(form), method: :delete, data: { confirm: 'Are you sure to delete this form?'}, class: 'btn-circle btn-sm btn-danger text-decoration-none' do
                %i.fas.fa-trash

app/views/survey_form/forms/new.html.haml
.d-flex.justify-content-center.py-4
  .w-75
    %h1 New Form

    = render 'form'

app/views/survey_form/forms/show.html.haml
= @form.name